[package]
name = "memory-map-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.0"
async-graphql-axum = "7.0"
axum = "0.8"
config = "0.15"
deadpool = "0.12"
deadpool-postgres = { version = "0.14", features = ["rt_tokio_1", "serde"] }
dotenvy = "0.15"
futures = "0.3"
futures-util = "0.3"
minio = "0.3"
refinery = { version = "0.8", features = ["tokio-postgres"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.47", features = ["full"] }
tokio-postgres = "0.7"
tower = { version = "0.5", features = ["util"] }
tracing = "0.1"
tracing-subscriber = "0.3"
