{
  description = "A Nix-flake-based Rust development environment";

  inputs = {
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1";
    nixpkgs-unstable.url = "github:nixos/nixpkgs/nixos-unstable";
    rustfs-src = {
      url = "github:rustfs/rustfs/1.0.0-beta.4";
      flake = false;
    };
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    fenix = {
      url = "github:nix-community/fenix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    fenix-monthly = {
      url = "github:nix-community/fenix/monthly";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    flake-parts.url = "github:hercules-ci/flake-parts";
    systems.url = "github:nix-systems/default";
    process-compose-flake.url = "github:Platonic-Systems/process-compose-flake";
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    git-hooks = {
      url = "github:cachix/git-hooks.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    inputs:
    inputs.flake-parts.lib.mkFlake { inherit inputs; } (
      top@{
        config,
        withSystem,
        moduleWithSystem,
        ...
      }:
      {
        imports = [
          # Optional: use external flake logic, e.g.
          # inputs.foo.flakeModules.default
          inputs.process-compose-flake.flakeModule
          inputs.flake-parts.flakeModules.easyOverlay
        ];
        # flake = {
        #   # Put your original flake attributes here.
        # };
        # systems for which you want to build the `perSystem` attributes
        systems = import inputs.systems;
        perSystem =
          {
            self',
            pkgs,
            config,
            lib,
            final,
            system,
            ...
          }:
          let
            rustToolchain =
              with inputs.fenix.packages.${pkgs.stdenv.hostPlatform.system};
              combine [
                stable.clippy
                stable.rustc
                stable.cargo
                inputs.fenix-monthly.packages.${pkgs.stdenv.hostPlatform.system}.latest.rustfmt
                stable.rust-src
                # For Leptos
                targets.wasm32-unknown-unknown.stable.rust-std
              ];
            rustfsPkgs = pkgs.extend (import inputs.rust-overlay);
            rustfsToolchain = rustfsPkgs.rust-bin.stable.latest.default.override {
              extensions = [ "rust-src" ];
            };
            rustfsRustPlatform = pkgs.makeRustPlatform {
              cargo = rustfsToolchain;
              rustc = rustfsToolchain;
            };
            rustfsPackage = pkgs.callPackage ./packages/rustfs.nix {
              rustPlatform = rustfsRustPlatform;
              rustfsSrc = inputs.rustfs-src;
            };

            dbName = "db";
            postgresPort = 5432;
            postgresDataDir = "data/postgres";
            postgresPackage = pkgs.postgresql.withPackages (postgresExtensions: [
              postgresExtensions.postgis
            ]);
            postgresHbaConf = pkgs.writeText "pg_hba.conf" ''
              # Generated by Nix
              local all all trust
              host all all 127.0.0.1/32 trust
              host all all ::1/128 trust
              local replication all trust
              host replication all 127.0.0.1/32 trust
              host replication all ::1/128 trust
            '';
            postgresInit = pkgs.writeShellApplication {
              name = "memory-map-postgres-init";
              runtimeInputs = [
                postgresPackage
                pkgs.coreutils
              ];
              text = ''
                set -euo pipefail

                PGDATA="$(readlink -m "${postgresDataDir}")"
                export PGDATA
                mkdir -p "$PGDATA"

                if [ -s "$PGDATA/PG_VERSION" ]; then
                  echo "PostgreSQL data directory already initialized: $PGDATA"
                  exit 0
                fi

                initdb --locale=C --encoding=UTF8 -D "$PGDATA"
              '';
            };
            postgresStart = pkgs.writeShellApplication {
              name = "memory-map-postgres-start";
              runtimeInputs = [
                postgresPackage
                pkgs.coreutils
              ];
              text = ''
                set -euo pipefail

                PGDATA="$(readlink -m "${postgresDataDir}")"
                export PGDATA

                exec postgres \
                  -D "$PGDATA" \
                  -c listen_addresses=127.0.0.1 \
                  -c port=${toString postgresPort} \
                  -c hba_file=${postgresHbaConf} \
                  -c unix_socket_directories=
              '';
            };
            postgresBootstrap = pkgs.writeShellApplication {
              name = "memory-map-postgres-bootstrap";
              runtimeInputs = [
                postgresPackage
                pkgs.gnugrep
              ];
              text = ''
                set -euo pipefail

                export PGHOST=127.0.0.1
                export PGPORT=${toString postgresPort}
                export PGDATABASE=postgres
                export PGCONNECT_TIMEOUT=5

                if ! psql -v ON_ERROR_STOP=1 -tAc "SELECT 1 FROM pg_database WHERE datname = '${dbName}'" | grep -qx 1; then
                  createdb "${dbName}"
                fi

                psql -v ON_ERROR_STOP=1 -tAc "SELECT name FROM pg_available_extensions WHERE name = 'postgis'" | grep -qx postgis
              '';
            };
            postgresTest = pkgs.writeShellApplication {
              name = "memory-map-postgres-test";
              runtimeInputs = [
                postgresPackage
                pkgs.gnugrep
              ];
              text = ''
                set -euo pipefail

                psql -h 127.0.0.1 -p ${toString postgresPort} -d ${dbName} -v ON_ERROR_STOP=1 -c 'SELECT version();'
                psql -h 127.0.0.1 -p ${toString postgresPort} -d ${dbName} -v ON_ERROR_STOP=1 -tAc "SELECT name FROM pg_available_extensions WHERE name = 'postgis'" | grep -qx postgis
              '';
            };

            rustfsDataDir = "data/rustfs";
            rustfsApiAddress = "127.0.0.1:9000";
            rustfsConsoleAddress = "127.0.0.1:9001";
            s3EndpointUrl = "http://${rustfsApiAddress}";
            s3Region = "us-east-1";
            s3BucketName = "memory-map";
            s3AccessKey = "memorymapdev";
            s3SecretKey = "memorymapdevsecret";
            rustfsStart = pkgs.writeShellApplication {
              name = "memory-map-rustfs-start";
              runtimeInputs = [
                rustfsPackage
                pkgs.coreutils
              ];
              text = ''
                set -euo pipefail

                data_dir="$(readlink -m "${rustfsDataDir}")"
                mkdir -p "$data_dir"
                exec rustfs server "$data_dir"
              '';
            };
            rustfsBootstrap = pkgs.writeShellApplication {
              name = "memory-map-rustfs-bootstrap";
              runtimeInputs = [
                pkgs.coreutils
                pkgs.curl
                pkgs.gnugrep
              ];
              text = ''
                set -euo pipefail

                health_body="$(mktemp)"
                response_body="$(mktemp)"
                trap 'rm -f "$health_body" "$response_body"' EXIT

                curl --fail --silent --show-error --max-time 5 --output "$health_body" "${s3EndpointUrl}/health/ready"
                if ! grep -Eq '"service"[[:space:]]*:[[:space:]]*"rustfs-endpoint"' "$health_body"; then
                  cat "$health_body" >&2
                  echo "RustFS readiness probe did not identify a RustFS service at ${s3EndpointUrl}" >&2
                  exit 1
                fi

                auth_args=(
                  --aws-sigv4 "aws:amz:${s3Region}:s3"
                  --user "${s3AccessKey}:${s3SecretKey}"
                  --silent
                  --show-error
                  --max-time 5
                )

                curl --fail "''${auth_args[@]}" "${s3EndpointUrl}/" >/dev/null

                bucket_status="$(curl "''${auth_args[@]}" --head --output "$response_body" --write-out "%{http_code}" "${s3EndpointUrl}/${s3BucketName}" || true)"
                case "$bucket_status" in
                  200)
                    exit 0
                    ;;
                  404)
                    ;;
                  *)
                    cat "$response_body" >&2
                    echo "Failed to check bucket ${s3BucketName}; HTTP $bucket_status" >&2
                    exit 1
                    ;;
                esac

                http_code="$(curl "''${auth_args[@]}" --request PUT --output "$response_body" --write-out "%{http_code}" "${s3EndpointUrl}/${s3BucketName}" || true)"
                case "$http_code" in
                  200|409)
                    ;;
                  *)
                    cat "$response_body" >&2
                    echo "Failed to create bucket ${s3BucketName}; HTTP $http_code" >&2
                    exit 1
                    ;;
                esac

                bucket_status="$(curl "''${auth_args[@]}" --head --output "$response_body" --write-out "%{http_code}" "${s3EndpointUrl}/${s3BucketName}" || true)"
                if [ "$bucket_status" != 200 ]; then
                  cat "$response_body" >&2
                  echo "Failed to verify bucket ${s3BucketName}; HTTP $bucket_status" >&2
                  exit 1
                fi
              '';
            };

            treefmtEval = inputs.treefmt-nix.lib.evalModule pkgs {
              # Cargo.toml lives at the repo root (one level above devenv/).
              projectRootFile = "Cargo.toml";
              programs = {
                nixfmt.enable = true;
                rustfmt = {
                  enable = true;
                  package = rustToolchain;
                };
                prettier = {
                  enable = true;
                  includes = [
                    "*.md"
                    "*.yml"
                    "*.yaml"
                  ];
                };
              };
              settings.formatter.tombi = {
                command = "${inputs.nixpkgs-unstable.legacyPackages.${system}.tombi}/bin/tombi";
                options = [
                  "format"
                  "--offline"
                ];
                includes = [ "*.toml" ];
              };
              settings.global.excludes = [ "frontend/pnpm-lock.yaml" ];
            };

            pre-commit-check = inputs.git-hooks.lib.${system}.run {
              src = ./..;
              hooks = {
                treefmt = {
                  enable = true;
                  package = treefmtEval.config.build.wrapper;
                };
                # These run on pre-push because whole-project tools do not mix
                # well with pre-commit's partial-file staging behaviour.
                clippy = {
                  enable = true;
                  entry = "${pkgs.just}/bin/just clippy";
                  pass_filenames = false;
                  always_run = true;
                  stages = [ "pre-push" ];
                };
                cargo-doc = {
                  enable = true;
                  entry = "${pkgs.just}/bin/just doc";
                  pass_filenames = false;
                  always_run = true;
                  stages = [ "pre-push" ];
                };
              };
            };
          in
          {
            # Recommended: move all package definitions here.
            # e.g. (assuming you have a nixpkgs input)
            # packages.foo = pkgs.callPackage ./foo/package.nix { };
            # packages.bar = pkgs.callPackage ./bar/package.nix {
            #   foo = config.packages.foo;
            # };

            formatter = treefmtEval.config.build.wrapper;

            checks = {
              formatting = treefmtEval.config.build.check self'.self;
              inherit pre-commit-check;
            };

            _module.args.pkgs = import inputs.nixpkgs {
              inherit system;
              config.allowUnfree = true;
              overlays = [
                (final: _prev: {
                  unstable = import inputs.nixpkgs-unstable {
                    inherit (final) system;
                    config.allowUnfree = true;
                  };
                })
              ];
            };

            overlayAttrs = {
              inherit (config.packages) rustToolchain rustfs;
            };

            packages.rustToolchain = rustToolchain;
            packages.rustfs = rustfsPackage;

            # `process-compose.foo` will add a flake package output called "foo".
            # Therefore, this will add a default package that you can build using
            # `nix build` and run using `nix run`.
            process-compose."default" = {
              settings = {
                ordered_shutdown = true;
                processes = {
                  pg1-init.command = postgresInit;
                  pg1 = {
                    command = postgresStart;
                    depends_on."pg1-init".condition = "process_completed_successfully";
                    shutdown = {
                      signal = 2;
                      timeout_seconds = 10;
                    };
                    readiness_probe = {
                      exec.command = "${postgresPackage}/bin/pg_isready -h 127.0.0.1 -p ${toString postgresPort} -d postgres";
                      initial_delay_seconds = 1;
                      period_seconds = 2;
                      timeout_seconds = 5;
                      success_threshold = 1;
                      failure_threshold = 10;
                    };
                    availability = {
                      restart = "on_failure";
                      max_restarts = 5;
                    };
                  };
                  pg1-bootstrap = {
                    command = postgresBootstrap;
                    depends_on."pg1".condition = "process_healthy";
                  };
                  pgweb = {
                    environment.PGWEB_DATABASE_URL = "postgres://127.0.0.1:${toString postgresPort}/${dbName}";
                    command = pkgs.pgweb;
                    depends_on."pg1-bootstrap".condition = "process_completed_successfully";
                  };
                  pg1-test = {
                    command = postgresTest;
                    depends_on."pg1-bootstrap".condition = "process_completed_successfully";
                  };
                  rustfs = {
                    command = rustfsStart;
                    environment = {
                      RUSTFS_ACCESS_KEY = s3AccessKey;
                      RUSTFS_SECRET_KEY = s3SecretKey;
                      RUSTFS_ADDRESS = rustfsApiAddress;
                      RUSTFS_CONSOLE_ENABLE = "true";
                      RUSTFS_CONSOLE_ADDRESS = rustfsConsoleAddress;
                      RUSTFS_REGION = s3Region;
                      RUSTFS_HEALTH_ENDPOINT_ENABLE = "true";
                    };
                    shutdown = {
                      signal = 15;
                      timeout_seconds = 5;
                    };
                    readiness_probe = {
                      exec.command = lib.getExe rustfsBootstrap;
                      initial_delay_seconds = 2;
                      period_seconds = 5;
                      timeout_seconds = 8;
                      success_threshold = 1;
                      failure_threshold = 6;
                    };
                    availability = {
                      restart = "on_failure";
                      max_restarts = 3;
                    };
                  };
                };
              };
            };

            devShells.default = pkgs.mkShell {
              # Alias for `nativeBuildInputs`
              # https://discourse.nixos.org/t/difference-between-buildinputs-and-packages-in-mkshell/60598/10
              packages = [
                pkgs.bashInteractive
                config.packages.rustToolchain
                config.process-compose."default".outputs.package
                postgresPackage
                pkgs.openssl
                pkgs.pkg-config
                pkgs.cargo-deny
                pkgs.cargo-edit
                pkgs.bacon
                pkgs.rust-analyzer
                pkgs.gh
                # Stable didn't yet have cargo-generate, so we're using unstable here
                pkgs.unstable.cargo-generate
                pkgs.just
                pkgs.pnpm
                pkgs.nodejs-slim
                pkgs.graphql-client
                # For Leptos
                pkgs.leptosfmt
                pkgs.trunk
                # https://github.com/trunk-rs/trunk/issues/732#issuecomment-2391810077
                pkgs.dart-sass
                # Stable had 0.2.105 and we needed 0.2.106, so we're using unstable here
                pkgs.unstable.wasm-bindgen-cli
                # Needed for building in release mode
                pkgs.binaryen
                # For link checking in markdown
                pkgs.lychee
                # pkgs.tailwindcss
                # For finding function calls
                pkgs.ast-grep
                # For ASCII-only lint check in `just doc`
                pkgs.ripgrep
              ];

              env = {
                # Required by rust-analyzer
                RUST_SRC_PATH = "${config.packages.rustToolchain}/lib/rustlib/src/rust/library";
                # Required by minio-rs dependency
                LD_LIBRARY_PATH = lib.makeLibraryPath [ pkgs.openssl ];
              };

              inherit (pre-commit-check) shellHook;
            };
          };
      }
    );
}
